# CMPUT 391 Team 3
# Authors: Colby Warkentin(1169034) and Yiming Liu (1245022)
# Function: Creates the two class files for handling images

build:
	javac WEB-INF/classes/UploadImage.java
	javac WEB-INF/classes/GetOnePic.java

clean:
	-rm -f WEB-INF/classes/UploadImage.class
	-rm -f WEB-INF/classes/GetOnePic.class